version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: metrics_password
    ports:
      - "5432:5432"

  app:
    build: ./app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://metrics_user:metrics_password@db:5432/metrics_db
    ports:
      - "8000:8000"

volumes:
  pgdata:
